#import <HTML/CanvasRenderingContext2D.idl>

// https://html.spec.whatwg.org/multipage/imagebitmap-and-animations.html#imagebitmapsource
typedef (CanvasImageSource or
         Blob or
         ImageData) ImageBitmapSource;
